### ISSUE TITLE
Como desenvolvedor, quero implementar o comportamento dos aliens quando abatidos, para dar lógica ao jogo

### ISSUE THREAD

**Issue by rogerluan** [rogerluan/OCLM-PUC-Campinas-2016#10]
**Tasks** 
- [ ] Aumentar a velocidade do jogo quando metade dos aliens forem abatidos
- [ ] Terminar o jogo quando todos os aliens forem abatidos
- [ ] Oferecer opção de jogar novamente quando o jogo terminar (low-priority)

**Definição de Done** 
- O jogo aumenta a velocidade quando metade dos aliens são abatidos
- O jogo termina quando todos os aliens morrem
