### ISSUE TITLE
Como desenvolvedor quero implementar as ações do alien, para adicionar jogabilidade ao jogo

### ISSUE THREAD

**Issue by rogerluan** [rogerluan/OCLM-PUC-Campinas-2016#7]
**Tasks** 
- [ ] Acrescentar uma pontuação dependendo do tamanho do alien. 
- [ ] Remover o alien da tela e não mostrar mais nada em seu lugar.
- [ ] A cada ciclo, deslocar o grupo de aliens para uma das laterais.
- [ ] Descer uma linha e iniciar o deslocamento para o lado contrário caso o alien já tenha achado o limite desse deslocamento.
- [ ] Fazer com que os aliens da primeira fileira (a de baixo, mais próximas da nave do usuário) atirem, em momentos diferentes.

**Definição de Done** 
- Pontuação sendo incrementada de acordo com o tipo de alien.
- Remoção do alien ao ser atingido, sem alterar os aliens ao redor dele.
- Os aliens se deslocam corretamente
- Todos os aliens descem uma linha após atingir o limite da janela
- Os aliens invertem a direção conforme descem uma linha
- Aliens atiram periodicamente
