### ISSUE TITLE
Como desenvolvedor quero implementar as funções do tiro, para dar funcionalidade ao jogo

### ISSUE THREAD

**Issue by rogerluan** [rogerluan/OCLM-PUC-Campinas-2016#8]
**Tasks** 
- [ ] Fazer cada tiro da nave subir na mesma coluna da matriz até atingir um alien ou o topo do tabuleiro (tela)
- [ ] Remover o tiro e o alien se um tiro atingir um alien
- [ ] Remover o tiro se o tiro atingir o topo do tabuleiro (tela)
- [ ] Fazer com que a nave só possa atirar novamente quando não houver um tiro na tela
- [ ] Subtrair 5 pontos do jogador ao atirar
- [ ] Escolher uma determinada tecla do teclado para atirar

**Definição de Done** 
- Implementar e testar cada funcionalidade descrita acima, e garantir que tudo funciona.
