### ISSUE TITLE
Como desenvolvedor, quero implementar as funcionalidades da nave, para melhorar a jogabilidade

### ISSUE THREAD

**Issue by rogerluan** [rogerluan/OCLM-PUC-Campinas-2016#9]
**Tasks** 
- [ ] Movimentar a nave utilizando as teclas `a` e `d` do teclado
- [ ] Exibir animação de destruição da nave, quando ela for atingida (low-priority, optional)
- [ ] Atribuir 3 vidas extras à nave, além da vida que o jogador inicia o jogo.

**Definição de Done** 
- Consegue movimentar a nave pela tecla corretamente, utilizando as dadas teclas
- O jogador perde o jogo quando atingido 4 vezes.
